[package]
name = "qwc_hir_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
qwc_ast = { path = "../qwc_ast" }
qwc_hir = { path = "../qwc_hir" }
qwc_arena = { path = "../qwc_arena" }
qwc_diagnostic = { path = "../qwc_diagnostic" }
qwc_string_interner = { path = "../qwc_string_interner" }
qwc_resolve = { path = "../qwc_resolve" }
qwc_mangling = { path = "../qwc_mangling" }
qwc_comptime = { path = "../qwc_comptime" }
