[package]
name = "qwc_hir"
version = "0.1.0"
edition = "2024"

[dependencies]
owo-colors = "4.4.0"
qwc_arena = { path = "../qwc_arena" }
qwc_string_interner = { path = "../qwc_string_interner" }
qwc_diagnostic = { path = "../qwc_diagnostic" }
qwc_dump = { path = "../qwc_dump" }
rustc-hash = "2.1.3"
thin-vec = "0.2.19"
serde = { version = "1.0.229", features = ["derive"] }
