[package]
name = "qwc_mir_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
qwc_hir = { path = "../qwc_hir" }
qwc_mir = { path = "../qwc_mir" }
qwc_comptime = { path = "../qwc_comptime" }
qwc_diagnostic = { path = "../qwc_diagnostic" }
qwc_mangling = { path = "../qwc_mangling" }
qwc_string_interner = { path = "../qwc_string_interner" }
rustc-hash = "2.1.3"
